# Feature Extraction 🔩
- Most classic machine learning algorithms can't take in raw text.
- Instead, we need to perform a feature "extraction" from the raw text to pass numerical features to the machine learning algorithm.
    - Counter Vectorization | Term-Frequency | Document Frequency.

In [13]:
# Count Vectorization
messages = ["Hey, lets go to the game today!",
           "Call your sister.",
           "Want to go walk your dogs?"]

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [37]:
vect = CountVectorizer()
X = vect.fit_transform(messages)

In [39]:
print(X.toarray())

[[0 0 1 1 1 1 0 1 1 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 1 0 1 0 0 0 0 1 0 1 1 1]]

In [41]:
print(vect.get_feature_names_out())

['call' 'dogs' 'game' 'go' 'hey' 'lets' 'sister' 'the' 'to' 'today' 'walk'
 'want' 'your']

- An alternative to CountVectorizer is TfidfVectorizer. It also creates a document term matrix from our messages.
- However, instead of filling the DTM with token counts, it calculates term frequency-inverse document frequency value for each word(TF-IDF).
    ```Term frequency tf(t,d): is the raw count of a term in a document, i.e. the number of times that term t occurs in the document d.```

#### Ordinal Categorical Data:Context

- How satisfied are you with the service?
    - Very dissatisfied
    - Dissatisfied
    - Neutral
    - Satisfied
    - Very satisfied
- How would you rate the quality of the food?
    - Bad
    - Good
    - Very Good
    - Excellent

In [84]:
import pandas as pd
import numpy as np

service = ["Very dissatisfied", "Dissatisfied", "Neutral", "Satisfied", "Very satisfied"]
quality = ["Bad", "Good", "Very Good", "Excellent"]

survey = {
    "services": ["Very dissatisfied", "Dissatisfied", "Neutral", "Satisfied", "Very satisfied", "Very dissatisfied"],
    "food": ["Bad", "Good", "Very Good", "Excellent", "Good", "Bad"]  
}

type_client = [0, 0, 1, 1, 0, 1]

pd.DataFrame(survey)

            services       food
0  Very dissatisfied        Bad
1       Dissatisfied       Good
2            Neutral  Very Good
3          Satisfied  Excellent
4     Very satisfied       Good
5  Very dissatisfied        Bad

### Ordinal Econder

In [94]:
from sklearn.preprocessing import OrdinalEncoder
data_ord = pd.DataFrame(survey)
codefider = OrdinalEncoder(categories =[service,quality])
data_ord = pd.DataFrame(codefider.fit_transform(data_ord),columns=["service","food"])
print(data_ord)
print("\nCategories\n")
print(codefider.categories_)

   service  food
0      0.0   0.0
1      1.0   1.0
2      2.0   2.0
3      3.0   3.0
4      4.0   1.0
5      0.0   0.0

Categories

[array(['Very dissatisfied', 'Dissatisfied', 'Neutral', 'Satisfied',
       'Very satisfied'], dtype=object), array(['Bad', 'Good', 'Very Good', 'Excellent'], dtype=object)]

### Codefider OneHotEncoder

In [100]:
from sklearn.preprocessing import OneHotEncoder
datos_one = pd.DataFrame(survey)
codefider = OneHotEncoder()
print(codefider.fit_transform(datos_one))

  (0, 3)	1.0
  (0, 5)	1.0
  (1, 0)	1.0
  (1, 7)	1.0
  (2, 1)	1.0
  (2, 8)	1.0
  (3, 2)	1.0
  (3, 6)	1.0
  (4, 4)	1.0
  (4, 7)	1.0
  (5, 3)	1.0
  (5, 5)	1.0

In [102]:
print(codefider.fit_transform(datos_one).toarray())

[[0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0.]]

In [106]:
data_one = pd.DataFrame(codefider.fit_transform(datos_one).toarray(),columns = np.concatenate(codefider.categories_))
data_one

,Dissatisfied,Neutral,Satisfied,Very dissatisfied,Very satisfied,Bad,Excellent,Good,Very Good
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0